### PR TITLE
Change password form

### PR DESCRIPTION
**Pull request by alinabudukina**
**The goal of this PR is to create a modal where we can change the password of the connected user.** 

1. I used some react libraries like emotion and reach for the modal’s UI. That’s why you can find `css in js` implementation.
2. I created a `reusable button` component that is basically like the original one: it has the same css properties but the difference is that it accepts also the new props that we pass. I needed that to change the size for exemple. Would be a good idea to replace the current submit button with the new one.
3. Modal logic can be complicated to understand, I was inspired by Kent C Dodds solution that is called `compound components`. It’s an advanced react pattern that helps to share state and logic within components using the `React.createContext API.`

You can read more about it in the original article: https://kentcdodds.com/blog/compound-components-with-react-hooks 

**Issues:**

1. The first problem is that when we open the modal, we see the white background with the navigation bar. I don’t know why and how to fix that.
2. The second problem is that when the new password is OK and changed after we click on the `save button` the modal is not closed. I was trying to close it with `refresh()` function that updates the page info, but apparently there is a react state error in console. No solution for the moment.
3. I didn’t encrypt the password, means that the client sends raw data to the server. Not great.

### CODE REVIEW

**Review by margauxln — APPROVED** [review]

**Comment by Sabevi** [comment]
Screenshot 2023-01-23 at 20 24 06
Screenshot 2023-01-23 at 20 24 13
Je ne vois pas ta branche à cause de ces erreurs, comment peux-je les résoudre ?

**Comment by Sabevi** [comment]
J'ai fait un npm install, mais il restent ces erreurs:
Screenshot 2023-01-23 at 20 26 34

**Comment by Sabevi** [comment]
Screenshot 2023-01-23 at 20 27 19
Il faut que tu te mettes à jour avec main

**Comment by Sabevi** [comment]
En version mobile, je trouve que tes polices sont un peu trop grandes dans les titres
Screenshot 2023-01-23 at 20 29 34

**Comment by Sabevi** [comment]
Voici les beugs que je vois au niveau de ta modale:

**Comment by Sabevi** [comment]
Par rapport à ton issue
======
 "The second problem is that when the new password is OK and changed after we click on the save button the modal is not closed. I was trying to close it with refresh() function that updates the page info, but apparently there is a react state error in console. No solution for the moment.
=====

Pour moi ce n'est pas la fonction refresh() qui va supprimer ta modale, il faut que quand l'utilisateur submit son nouveau mot de passe, il y ait la même action que quand il veut fermer la modale (en cliquant sur X) qui soit activée. Tu vois ce que je veux dire ?

**Comment by Sabevi** [comment]
Je vois que dans la page MyProfile <div> Loading </div> n'a pas été remplacé avec le composant custom que j'ai crée, je ne sais pas s'il y a d'autres endroits ou il faudrait l'ajouter

**Review by Sabevi — CHANGES_REQUESTED** [review]
Hello, je t'ai mis mes commentaires

**Comment by Sabevi** [comment]
A la toute fin rappelle toi de mettre toute ta branche dans un seule commit (git reset --soft HEAD~28)
28 est ton nombre actuel, ça pourra changer

**Comment by alinabudukina** [comment]
I marked all the resolved issues with an emoji @Sabevi 

1. Personally I don’t see any compilation problems, could you please give it another try or may be you know how can I fix that? 
3. Still no a quick solution for the closing modal. I added some text so that the user will be notified if the pswd was changes successfully. Finally that's a great point that I will mention in my todo at the final work as a thing to improve.
4. Unfourtunately an eye implementation on the input component requires too much changes, because the current component doesn’t fit in. I will also mention that it my todo list as a feature to be added and improved.
5. I just use a `squash and merge` button at the end if you don't mind.

**Review by Sabevi — APPROVED** [review]

**Pull request merged**
